Sp2023 167 row render h5p row
h5p/h5p-row pull request #2
Opened 2023-08-22 08:26 UTC by odacolquhoun

2023-08-22 09:26 UTC, Camtrup reviewed
Nicely done! One comment and it should be gucci💸. But done very elegantly!!!

2023-08-22 09:26 UTC, Camtrup commented on h5p-row.js
> +        var column = document.createElement('div');
This should recieve some inline styling to fit the width and paddings that come with the forked column:

<img width="562" alt="image" src="https://github.com/h5p/h5p-row/assets/42533113/5f1f20e6-4073-4fe2-8c67-b9079b7d6037">

2023-08-22 09:26 UTC, Camtrup commented on h5p-row.js
> +    console.log(params);
Should remove this

2023-08-23 13:50 UTC, Languafe commented on h5p-row.js
> +      wrapper.classList.add('h5p-row');
Beware that the same class is added to the container inside the `attach` method. It's probably okay, but could potentially be confusing if trying to apply styles.

2023-08-23 13:51 UTC, Languafe commented on h5p-row.js
> +        var column = document.createElement('div');
I think `const` and `let` is cooler than `var`, but I don't know what the kids today think.

2023-08-24 06:49 UTC, Languafe requested changes
Super close, please review my suggestion for changing the class we add to the container for each column.

2023-08-24 06:49 UTC, Languafe commented on h5p-row.js
> +        column.classList.add('h5p-column');
To match what H5P.Column does, add the class `h5p-row-content` here instead. H5P.Column itself will add the `h5p-column` class (but H5P.Row should not rely on this).

```suggestion
        column.classList.add('h5p-row-content');
```

2023-08-24 06:49 UTC, Languafe commented on h5p-row.css
> +.h5p-column {
Change to match the suggestion below.
```suggestion
.h5p-row-content {
```

2023-08-24 06:59 UTC, Languafe approved these changes

2023-08-24 07:00 UTC, merged